import math
import logging
from database import DatabaseManager

logger = logging.getLogger("roadsense.data_fusion")

class DataFusionEngine:
    """
    Multi-Source Data Fusion Engine
    Cross-references citizen reports, CV detections, and historical logs 
    to assign an AI Confidence Score and automatically draft Work Orders.
    """
    
    # Weighting Logic Explanation:
    # 1. Computer Vision (Weight: 40%) - Direct visual confirmation provides highest objective certainty.
    # 2. Citizen Reports (Weight: 30%) - Ground truth human observation, but subjective.
    # 3. IoT/Telemetry (Weight: 20%) - Physical vibrations/stress confirm structural irregularities.
    # 4. Historical Age (Weight: 10%) - Roads older than 3 years inherently have a higher probability of defects.
    WEIGHTS = {
        'cv_weight': 0.40,
        'citizen_weight': 0.30,
        'iot_weight': 0.20,
        'history_weight': 0.10
    }
    
    @staticmethod
    def calculate_confidence_and_draft_order(road_id: str, road_name: str, cv_defects: int, citizen_reports: int, avg_vibration: float, road_age_days: int) -> dict:
        """
        Calculates fusion confidence score. 
        If confidence > 75%, automatically drafts a pending work order.
        """
        score = 0.0
        
        # 1. CV Impact (Max 40 points) - 1 defect = 10 points
        cv_score = min(40, cv_defects * 10.0)
        score += cv_score
        
        # 2. Citizen Report Impact (Max 30 points) - 1 report = 15 points
        cit_score = min(30, citizen_reports * 15.0)
        score += cit_score
        
        # 3. IoT Vibration Impact (Max 20 points) - normal ~1.0, critical > 4.0
        iot_score = min(20, (avg_vibration / 4.0) * 20.0) if avg_vibration else 0
        score += iot_score
        
        # 4. History Impact (Max 10 points) - 3 years (1095 days) = max points
        hist_score = min(10, (road_age_days / 1095.0) * 10.0)
        score += hist_score
        
        action_taken = "Monitoring"
        auto_work_order_id = None
        
        # Threshold Logic
        if score > 75.0:
            action_taken = "Auto-Drafted Work Order"
            # 1 = System/Admin User ID
            auto_work_order_id = DatabaseManager.add_work_order(
                road_id=road_id,
                road_name=road_name,
                work_type="Fusion-Triggered Critical Repair",
                created_by=1, 
                estimated_cost=15000,
                notes=f"Auto-generated by AI Data Fusion. Confidence Score: {score:.1f}%"
            )
            logger.info(f"Fusion Engine auto-drafted Work Order #{auto_work_order_id} for {road_name}")
            
        return {
            "fusion_confidence_score": round(score, 2),
            "breakdown": {
                "cv_contribution": round(cv_score, 2),
                "citizen_contribution": round(cit_score, 2),
                "iot_contribution": round(iot_score, 2),
                "history_contribution": round(hist_score, 2)
            },
            "action_taken": action_taken,
            "auto_drafted_work_order_id": auto_work_order_id
        }
